content/urls.py
from django.urls import path
from .views import UploadFeed #UploadReply
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('upload', UploadFeed.as_view()),
    #path('reply', UploadReply.as_view()),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minstagram/urls.py
from django.contrib import admin
from django.urls import path, include

from posts import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('posts.urls')),
    path("common/", include('user.urls')),
    #path("urls/", include('user.urls')),
]

posts/urls.py
from django.urls import path, include
from .views import Main
from django.conf import settings
from django.conf.urls.static import static

app_name = "posts"

urlpatterns = [
    path('', Main.as_view(), name="main"),  
    path('content/', include('content.urls')),
    path('user/', include('user.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import Login, Join

app_name = 'user'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('join/', Join.as_view(), name='join'),
]

content/models.py
from django.db import models

class Feed(models.Model):
    content       = models.TextField()
    image         = models.TextField()
    profile_image = models.TextField()
    user_id       = models.TextField()
    like_count    = models.IntegerField()

# class Reply(models.Model):
#     feed_id = models.IntegerField(default=0)
#     email = models.EmailField(default='')
#     reply_content = models.TextField()

posts/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

# Create your models here.
class User(AbstractBaseUser):
    name = models.CharField(max_length=30, blank=True, null=True)
    email = models.EmailField(verbose_name='email', max_length=100, blank=True, null=True, unique=True)
    user_id = models.CharField(max_length=30, blank=True, null=True)
    thumbnail = models.CharField(max_length=256, default='default_profile.jpg', blank=True, null=True)

    USERNAME_FIELD = 'id'
    REQUIRED_FIELDS = ['user_id']

    def __str__(self):
        return self.user_id

    @property
    def is_staff(self):
        return self.is_admin

    class Meta:
        db_table = 'users'

content/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from content.models import Feed # Reply
from rest_framework.response import Response
import os
from minstagram.settings import MEDIA_ROOT, MEDIA_URL
from uuid import uuid4

class UploadFeed(APIView):
    def post(self, request):
        file = request.FILES['file']
        uuid_name = uuid4().hex
        save_path = os.path.join(MEDIA_ROOT, uuid_name)
        with open(save_path, 'wb+') as destination:
            for chunk in file.chunks():
                destination.write(chunk)
        content = request.data.get('content')
        image = uuid_name
        profile_image = request.data.get('profile_image')
        user_id = request.data.get('user_id')

        Feed.objects.create(content=content, image=image, profile_image=profile_image, user_id=user_id, like_count=0)

        return Response(status=200)
    

# class UploadReply(APIView):
#     def post(self, request):
#         feed_id = request.data.get('feed_id', None)
#         reply_content = request.data.get('reply_content', None)
#         email = request.session.get('email', None)

#         Reply.objects.create(feed_id=feed_id, reply_content=reply_content, email=email)

#         return Response(status=200)

posts/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from content.models import Feed
from user.models import User
from rest_framework.response import Response
import os
from minstagram.settings import MEDIA_ROOT, MEDIA_URL
from uuid import uuid4


class Main(APIView):
    def get(self, request):
        feed_list = Feed.objects.all().order_by('-id')
        email = request.session['email']

        if email is None:
            return render(request, "common/login.html")
        
        user = User.objects.filter(email=email).first()

        if user is None:
            return render(request, "common/login.html")
        
        return render(request, 'minstagram/main.html', context=dict(feed_list=feed_list, user=user))

class UploadFeed(APIView):
    def post(self, request):
        file = request.FILES['file']
        uuid_name = uuid4().hex
        save_path = os.path.join(MEDIA_ROOT, uuid_name)
        with open(save_path, 'wb+') as destination:
            for chunk in file.chunks():
                destination.write(chunk)
        content = request.data.get('content')
        image = uuid_name
        profile_image = request.data.get('profile_image')
        user_id = request.data.get('user_id')

        Feed.objects.create(content=content, image=image, profile_image=profile_image, user_id=user_id, like_count=0)

        return Response(status=200)

user/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from .models import User
from django.contrib.auth.hashers import make_password, check_password
from rest_framework.response import Response
from uuid import uuid4
import os
from minstagram.settings import MEDIA_ROOT


class Login(APIView):
    def get(self, request):
        return render(request, 'user/login.html')

    def post(self, request):
        email = request.data.get('email', None)
        password = request.data.get('password', None)
        if email is None:
            return Response(status=500, data=dict(message='이메일을 입력해주세요'))

        if password is None:
            return Response(status=500, data=dict(message='비밀번호를 입력해주세요'))

        user = User.objects.filter(email=email).first()

        if user is None:
            return Response(status=500, data=dict(message='입력정보가 잘못되었습니다.'))

        if check_password(password, user.password) is False:
            return Response(status=500, data=dict(message='입력정보가 잘못되었습니다.'))

        request.session['loginCheck'] = True
        request.session['email'] = user.email

        return Response(status=200, data=dict(message='로그인에 성공했습니다.'))


class Join(APIView):
    def get(self, request):
        return render(request, 'user/join.html')

    def post(self, request):
        password = request.data.get('password')
        email = request.data.get('email')
        user_id = request.data.get('user_id')
        name = request.data.get('name')

        if User.objects.filter(email=email).exists() :
            return Response(status=500, data=dict(message='해당 이메일 주소가 존재합니다.'))
        elif User.objects.filter(user_id=user_id).exists() :
            return Response(status=500, data=dict(message='사용자 이름 "' + user_id + '"이(가) 존재합니다.'))

        User.objects.create(password=make_password(password),
                            email=email,
                            user_id=user_id,
                            name=name)

        return Response(status=200, data=dict(message="회원가입 성공했습니다. 로그인 해주세요."))

templates/user/join.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <!-- jquery 사용하기 위해 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


    <title>Jinstagram login</title>
</head>
<style>
    .floating_form {
        margin: 0px 30px;
    }

    .floating_label {
        margin-top: -4px;
        font-size: 14px;
    }

    .floating_input {
        height: 50px !important;
        padding-top: 20px !important;
        font-size: 14px !important;
    }

</style>
<body style="background-color: #FAFAFA;height: 100%">
<div style="font-size: 14px;text-align: center;width: 100%;min-height: 100vh;display: flex; flex-direction: row; align-items: center; justify-content: center">
    <div>
        <div class="mb-3" style="background-color: white; width: 350px; height: 480px; border: 1px solid rgba(0, 0, 0, 0.18);">
            <div style="display: flex;align-items: center;justify-content: center">
                <img style="height: 50px; object-fit: contain; margin: 30px 0"
                        src="https://www.instagram.com/static/images/web/mobile_nav_type_logo-2x.png/1b47f9d0e595.png">
            </div>
            <div style="font-size:17px; font-weight:600; line-height: 20px; text-align: center; color: rgba(142,142,142,1); margin: 0 40px 20px">
                친구들의 사진과 동영상을 보려면 가입하세요.
            </div>
            <div class="form-floating mb-2 floating_form">
                <input type="email" class="floating_input form-control" id="floatingEmail"
                        placeholder="name@example.com">
                <label for="floatingEmail" class="floating_label">이메일 주소</label>
            </div>
            <div class="form-floating mb-2 floating_form">
                <input type="text" class="floating_input form-control" id="floatingName" placeholder="홍길동">
                <label for="floatingName" class="floating_label">성명</label>
            </div>
            <div class="form-floating mb-2 floating_form">
                <input type="text" class="floating_input form-control" id="floatingUserId" placeholder="hong">
                <label for="floatingUserId" class="floating_label">사용자 이름</label>
            </div>
            <div class="form-floating mb-3 floating_form">
                <input type="password" class="floating_input form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword" class="floating_label">비밀번호</label>
            </div>
            <div class="floating_form mb-3">
                <button id="button_join"  type="button" class="btn btn-primary" style="width: 100%"> 가입 </button>
            </div>
        </div>
        <div style="background-color: white; width: 350px; height: 70px; border: 1px solid rgba(0, 0, 0, 0.18);">
            <div style="margin-top: 25px">
                계정이 있으신가요? <a href="{% url 'user:login' %}" style="font-weight: bold; color: cornflowerblue;text-decoration: none; cursor: pointer">가입하기</a>
            </div>
        </div>
    </div>
</div>


<!-- Optional JavaScript; choose one of the two! -->
<script>
    $('#button_join').on('click',()=>{
        console.log('클릭했다.');
        let email = $('#floatingEmail').val();
        let name = $('#floatingName').val();
        let user_id = $('#floatingUserId').val();
        let password = $('#floatingPassword').val();
        console.log('이멜 :' + email + ', 이름 :'  + name + ', 사용자이름 :'  +  user_id + ', 비밀번호 :'  +  password);

        console.log(email, password, name, user_id);

        $.ajax({
            url: "/common/join/",
            data: {
                email: email,
                password: password,
                user_id: user_id,
                name: name
            },
            method: "POST",
            dataType: "json",
            success: function (data){
                alert(data.message);
                location.replace('{% url 'user:login' %}');
            },
            error:function (request, status, error){
                let data = JSON.parse(request.responseText);
                console.log(data.message);
                alert(data.message);
            }
        });


    });
</script>

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
-->
</body>
</html>

templates/user/login.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <!-- jquery 사용하기 위해 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <title>Jinstagram login</title>
</head>
<style>
    .floating_form {
        margin: 0px 30px;
    }

    .floating_label {
        margin-top: -4px;
        font-size: 14px;
    }

    .floating_input {
        height: 50px !important;
        padding-top: 20px !important;
        font-size: 14px !important;
    }

</style>
<body style="background-color: #FAFAFA;height: 100%">
<div style="font-size: 14px;text-align: center;width: 100%;min-height: 100vh;display: flex; flex-direction: row; align-items: center; justify-content: center">
    <div>
        <div class="mb-3" style="background-color: white; width: 350px; height: 380px; border: 1px solid rgba(0, 0, 0, 0.18);">
            <div style="display: flex;align-items: center;justify-content: center">
                <img style="height: 50px; object-fit: contain; margin: 30px 0"
                        src="https://www.instagram.com/static/images/web/mobile_nav_type_logo-2x.png/1b47f9d0e595.png">
            </div>
            <div class="form-floating mb-2 floating_form">
                <input type="email" class="floating_input form-control" id="floatingEmail"
                        placeholder="name@example.com">
                <label for="floatingEmail" class="floating_label">이메일 주소</label>
            </div>
            <div class="form-floating mb-3 floating_form">
                <input type="password" class="floating_input form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword" class="floating_label">비밀번호</label>
            </div>
            <div class="floating_form mb-3">
                <button id="button_login" type="button" class="btn btn-primary" style="width: 100%"> 로그인</button>
            </div>
            <div class="mb-2" style="display: flex; align-items: center; justify-content: space-between">
                <hr style="border:1px silver;margin-left: 30px;width: 100px">
                또는
                <hr style="border:1px silver;margin-right: 30px;width: 100px">
            </div>
            <div style="font-weight: bold; color: royalblue">
                테스트로 로그인 (둘러보기)
            </div>
        </div>
        <div style="background-color: white; width: 350px; height: 70px; border: 1px solid rgba(0, 0, 0, 0.18);">
            <div style="margin-top: 25px">
                계정이 없으신가요? <a href="{% url 'user:join' %}" style="font-weight: bold; color: cornflowerblue; text-decoration: none; cursor: pointer">가입하기</a>
            </div>
        </div>
    </div>


</div>


<!-- Optional JavaScript; choose one of the two! -->
<script>
    $('#button_login').on('click', ()=>{
        let email = $('#floatingEmail').val();
        let password = $('#floatingPassword').val();

        $.ajax({
            url: "/common/login/",
            data: {
                email: email,
                password: password
            },
            method: "POST",
            dataType: "json",
            success: function (data){
                location.replace('{% url 'posts:main' %}');
            },
            error:function (request, status, error){
                let data = JSON.parse(request.responseText);
                console.log(data.message);
                alert(data.message);
            }
        });
    });
</script>
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
-->
</body>
</html>